export const fixOrders = async () => {
    const orders = [
         {
          client: 'Аркадий Бобров',
          contact: '+375 44 5598599',
          clientAdress: 'Одинцова 23 1 224',
          title: 'Ноутбук',
          cost: 150,
          firm: 'Samsung',
          model: 'R515',
          sn: 'JSL8979SD79SD79SDSD',
          look: 'бу потерт',
          speed: 'стандарт',
          info: 'Профилактика системы охлаждения',
          problem: 'Профилактика'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          },
          {
            client: 'Ноутбук',
          contact: 'Stanislaw Lem',
          clientAdress: 1961,
          title: 1961,
          cost: 1961,
          firm: 1961,
          model: 1961,
          sn: 1961,
          look: 1961,
          speed: 1961,
          info: 'вотвотвот'
          }
    ]
    return orders
}